# print information during playbook execution / writing multiple plays in single book

- name: playbook 1
  hosts: local
  connection: local

  tasks:
   -name: task1
     ansible.builtin.debug:
      msg: "Hello"


- name: playbook 2
  hosts: local
  connection: local


  tasks:
   -name: task2
    ansible.builtin.debug:
      msg: "Hi"      