- name: simple variables
  hosts: local
  connection: local

  vars:  #play level variables
    COURSE: "AWS Devops"
    DURATION: "120hours"
    TRAINER: "Pushpa"

  tasks: 
    - name: print variable
      ansible.builtin.debug:
        msg: "course is {{ COURSE }}, duration is {{ DURATION }}, trainer is {{ TRAINER }}"
    
