- name: prompt variables
  hosts: local
  connection: local

  vars_prompt:
  - name: COURSE
    prompt: course name is
    
  - name: DURATION
    prompt: duration is
    private: false

  tasks: 
    - name: print the info
      ansible.builtin.debug:
       msg: course is {{ COURSE }}, duration is {{ DURATION }}  