- name: file variables
  hosts: localhost
  connection: local


  tasks:
    - name: course information
      ansible.builtin.debug:
        msg: course is {{ COURSE }}, duration is {{ DURATION }} 


        