- name: print a value greater than 10
  hosts: localhost
  connection: local

  vars:
    number: 90

  tasks: 
    - name: check and print value divisible by 2 
      ansible.builtin.debug:
        msg: "Given number {{ number }} is divisible by two"
      #when: number>10
      #when: number % 2 == 0
      when: number != 90 and number % 2 == 0


    #- name: check and print value less than 10
      #ansible.builtin.debug:
     #   msg: " Given number {{ number }} is less than 10"
      #when: number<10
      

