- name: undefined variables
  hosts: localhost
  connection: local

  tasks:
    - name: print default variables
      ansible.builtin.debug:
        msg: "Hi {{ pushpa | default ('female') }}"



    - name: convert string to list
      vars:
        fruitname: "'mango','banana'"
      ansible.builtin.debug:
        msg: "selling fruits: {{ fruitname | split (',')}}"  


    - name: convert map to list
      vars:
        course:
          name: aws
          duration: onemonth
          timing: 8:30AM
      ansible.builtin.debug:
        msg: "course details are: {{ course | dict2items }}"



    - name: list to map conversion
      vars:
        course:
        - {'key': 'name' , 'value': 'aws'}
        - {'key': 'tools' , 'value': 'git'}
      ansible.builtin.debug:
        msg: "course details are: {{ course | items2dict }}"  



    - name: lower to upper case
      vars:
        name: Chintakayala rAvi
      ansible.builtin.debug:
        msg: "Hey {{ name | upper }}"

    - name: min and max values
      vars:
        numbers: [1,9,56,47,9,4]
      ansible.builtin.debug:
        msg: "min and maximum number: {{ numbers | max }}"  



